version: "3"
services:
  promtail:
    image: grafana/promtail:2.4.0
    container_name: "promtail"
    volumes:
      - /var/log:/var/log
      - ./promtail:/etc/promtail
    # ports:
    #   - "1514:1514" # this is only needed if you are going to send syslogs
    restart: unless-stopped
    command: -config.file=/etc/promtail/promtail-config.yml
    environment:
        HTTP_PROXY: "http://199.100.16.100:3128"
        HTTPS_PROXY: "http://199.100.16.100:3128"
        NO_PROXY: "localhost, 127.0.0.0/8, loki"